### ISSUE TITLE
Compare with *stability* from Leary & Petchey

### ISSUE THREAD

**Issue by SamRPJRoss** [opetchey/response_diversity_how_to_measure#10]
Go that extra step and correlate response diversity with stability, as measured from Leary & Petchey. Involves recalculating response diversity based on species pairs.

**Comment by opetchey** [comment]
@SamRPJRoss This is now ready to be done! I understand that one of us will tackle it when we get a chance :)

**Comment by opetchey** [comment]
@SamRPJRoss First have a look at this issue #16 please

**Comment by SamRPJRoss** [comment]
I correlated our indices with stability using the Leary & Petchey data, with mixed results. Sometimes they do better than our *approximation* (issue #16) of the response diversity from Leary & Petchey - particularly the divergence (sign-sensitive) index. Sometimes they do about the same or worse (particularly the dissimilarity index). 

I just did the absolute most basic Pearson Correlations though (I couldn't see what the original models were) so maybe (probably!) there's a better model to fit (perhaps even something nonlinear?). 

Keen to hear your thoughts on where to go from here, @opetchey. I see 3 options: 1) We can write it up saying qualitatively most of the time the results are similar, or 2) we can try and pursue a better model or 3) better metric (which would likely fall under the benchmarking project, as it would going back to square 1 a bit for this paper I think).

**Comment by opetchey** [comment]
Hi Sam, am a bit behind with tasks. Will look at this soon. Owen
________________________________

**Comment by opetchey** [comment]
The modelling in Petchey & Leary 2009 were a collection of randomisation tests, with the test statistic being the slope of the relationship between stability and diversity. We did this to deal with non-independence. I guess one could rather use a mixed model of some kind.

**Comment by opetchey** [comment]
I added a summary graph (a coefficients plot) to the supplement... this could be used in the ms (after some beautifying). I also wrote some text in the supplement following that coefficients plot, which might be useful in the ms.

I suggest to go with your option 1 above, except that we say that the results are not the same, and point out how they are now, with the point being that we see that there are differences in performance, perhaps even results that one might expect (a sign senstive measure does explain the greatest variation in stability than any other), though really the results should be considered very preliminary. Hence the benchmarking project and response diversity network :)

**Comment by opetchey** [comment]
And sorry it took me a while to get to this.
And I'm on proper holiday next week and week after, i.e. no email etc.

**Comment by opetchey** [comment]
Thanks Sam. Let’s chat when I’m back… a few things we could talk about. Have a good couple of weeks, cheers, Owen

**Comment by opetchey** [comment]
Thanks Sam. Let’s chat when I’m back… a few things we could talk about. Have a good couple of weeks, cheers, Owen

**Comment by SamRPJRoss** [comment]
Note I'm marking this as closed since I've done the above and am writing it into the manuscript now. Thanks for your work on this, Owen!
