### ISSUE TITLE
Check how original r_cor and k_cor were calculated

### ISSUE THREAD

**Issue by SamRPJRoss** [opetchey/response_diversity_how_to_measure#13]
Check in the original files how r_cor and k_cor were correlated in Leary & Petchey (because they weren't identical when we recalculated them)

**Comment by opetchey** [comment]
I carefully checked the original code for Leary and Petchey and am satisfied that it was done appropriately and that we use correct values. However, there are multiple ways to do it, and Leary and Petchey is only one. When we did it yesterday, we were using a somewhat different method, and so did not find identical correlations. In the comparisons I recently made, the signs of the correlation.
